export const GET_PROFILE = "GET_PROFILE";
export const SET_PROFILE = "SET_PROFILE";
export const SELECT_PROFILE = "SELECT_PROFILE";
export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const RENAME_PROFILE = "RENAME_PROFILE";
export const UP_PROFILE = "UP_PROFILE";
export const DOWN_PROFILE = "DOWN_PROFILE";
